spring.application.name=onlinefoodapplication

#AWS configuration
aws.access.key=${ACCESS_KEY}
aws.secret.key=${SECRET_KEY}
aws.region=us-east-1
aws.s3.bucket.name=online-food-applications

#MYSQL connection

# MySQL Config

spring.datasource.url=jdbc:mysql://localhost:3308/onlinefoodapp
spring.datasource.username=root
spring.datasource.password=Sheik@5606

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret.key=bXlTdXBlclNlY3VyZUtleUZvckpXVEhTMjU2U2lnbmluZw==

#Razorpay

razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET_KEY}